import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import ReduxProvider from "@/app/redux/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ReduxProvider>
          <Header />
          <main className="flex-1 flex items-center justify-center">
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}